import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { createTinyDataset } from "@/test/fixtures/tiny-dataset";
import { wideFileInputs, writeWideCsv } from "@/test/fixtures/data/wide-writer";
import { importFiles } from "./index";
import { exportDatasetJson } from "./canonical-json";
import { parseWideCsv } from "./wide-csv";
import type { IssueSink } from "../normalize";

const sink = (file = "x.csv"): IssueSink => ({ file, issues: [] });
const codes = (s: IssueSink) => s.issues.map((i) => i.code);

describe("wide CSV import (acceptance)", () => {
  it("four files join to the same companies as the canonical JSON", async () => {
    const tiny = createTinyDataset();
    const canonical = await importFiles([{ name: "tiny.json", text: exportDatasetJson(tiny) }]);
    const wide = await importFiles(wideFileInputs(writeWideCsv(tiny)));
    expect(canonical.report.ok).toBe(true);
    expect(wide.report.ok).toBe(true);
    expect(wide.dataset?.companies).toEqual(canonical.dataset?.companies);
    expect(wide.dataset?.companies).toEqual(tiny.companies);
    expect(wide.files.map((f) => f.kind)).toEqual(["shareholding", "annual", "companies", "quarterly"]);
    expect(wide.report.annualRows).toBe(canonical.report.annualRows);
    expect(wide.report.quarterRows).toBe(canonical.report.quarterRows);
    expect(wide.report.shareholdingRows).toBe(canonical.report.shareholdingRows);
    expect(wide.report.issues.filter((i) => i.level !== "info")).toEqual([]);
  });

  it("records the files and their kinds in the dataset meta, and never marks user files synthetic", async () => {
    const wide = await importFiles(wideFileInputs(writeWideCsv(createTinyDataset())));
    const meta = wide.dataset?.meta;
    expect(meta?.isSynthetic).toBe(false);
    expect(meta?.source).toBe("user_import");
    expect(meta?.asOf).toBeNull();
    expect(meta?.importedAt).toBeNull();
    expect(meta?.files.map((f) => f.kind).sort()).toEqual(["annual", "companies", "quarterly", "shareholding"]);
  });

  it("labels files that describe themselves as fictional sample data", async () => {
    const wide = await importFiles(wideFileInputs(writeWideCsv(createTinyDataset(), {
      header: "Fictional sample data generated by Funda Scanner (seed 24301). It describes no real company.",
    })));
    expect(wide.report.ok).toBe(true);
    expect(wide.dataset?.meta.isSynthetic).toBe(true);
    expect(wide.dataset?.meta.notes.join(" ")).toMatch(/fictional sample data/);
  });

  it("imports the shipped templates without any warning", async () => {
    const files = ["companies", "annual", "quarterly", "shareholding"].map((n) => ({
      name: `${n}-template.csv`, text: readFileSync(`public/sample-data/templates/${n}-template.csv`, "utf8"),
    }));
    const out = await importFiles(files);
    expect(out.report.ok).toBe(true);
    expect(out.report.issues).toEqual([]);
    expect(out.dataset?.companies[0]).toMatchObject({ symbol: "EXAMPLE", company_type: "non_financial", fy_end_month: 3 });
    expect(out.dataset?.companies[0].annual).toHaveLength(2);
    expect(out.dataset?.companies[0].quarterly).toHaveLength(4);
    expect(out.dataset?.meta.isSynthetic).toBe(false);
  });
});

describe("parseWideCsv", () => {
  it("recognises headers by field name, label, metric id and unit suffix", () => {
    const s = sink("a.csv");
    const csv = 'Ticker,FY,"Revenue from operations (₹ Cr)",PAT,DPS,"Net profit attributable to owners",Capex\nabc,FY26,"1,200.5",(12),2,10,30\n';
    const out = parseWideCsv("annual", csv, s);
    expect(s.issues).toEqual([]);
    expect(out.annual).toHaveLength(1);
    expect(out.annual[0].symbol).toBe("ABC");
    expect(out.annual[0].row).toMatchObject({ fiscal_year: 2026, revenue: 1200.5, net_profit: -12, dividend_per_share: 2, net_profit_owners: 10, capex: 30, cogs: null });
  });

  it("skips comment lines and blank rows; counts data rows only", () => {
    const s = sink("q.csv");
    const csv = "# a comment, with \"quotes\nsymbol,period_end,revenue\n\n# another\nA,2026-06-30,10\nA,30/09/2026,11\n";
    const out = parseWideCsv("quarterly", csv, s);
    expect(out.rows).toBe(2);
    expect(out.comments).toEqual(['a comment, with "quotes', "another"]);
    expect(out.quarterly.map((q) => q.row.period_end)).toEqual(["2026-06-30", "2026-09-30"]);
    expect(out.quarterly[1].rowNo).toBe(2);
  });

  it("reports unknown and repeated columns, junk numbers and bad dates with row numbers", () => {
    const s = sink("q.csv");
    const csv = "symbol,period_end,revenue,colour,sales\nA,2026-06-30,abc,red,5\nB,not a date,1,blue,2\n";
    const out = parseWideCsv("quarterly", csv, s);
    expect(codes(s)).toEqual(["W112_UNKNOWN_COLUMN", "W112_UNKNOWN_COLUMN", "W111_NOT_A_NUMBER", "W117_BAD_DATE"]);
    expect(s.issues[2]).toMatchObject({ row: 1, symbol: "A", field: "revenue", file: "q.csv" });
    expect(s.issues[3]).toMatchObject({ row: 2, symbol: "B" });
    expect(out.quarterly).toHaveLength(1);
    expect(out.quarterly[0].row.revenue).toBeNull();
  });

  it("keeps the later duplicate period and the later duplicate company, with warnings", () => {
    const s1 = sink("a.csv");
    const a = parseWideCsv("annual", "symbol,fiscal_year,revenue\nA,2025,1\nA,2025,2\n", s1);
    expect(a.annual).toHaveLength(1);
    expect(a.annual[0].row.revenue).toBe(2);
    expect(codes(s1)).toEqual(["W113_DUPLICATE_PERIOD"]);
    const s2 = sink("c.csv");
    const c = parseWideCsv("companies", "symbol,name,isin\nA,First,\nA,Second,\n", s2);
    expect(c.companies.map((x) => x.name)).toEqual(["Second"]);
    expect(codes(s2)).toEqual(["W114_DUPLICATE_COMPANY"]);
  });

  it("skips rows without a symbol (warning) and requires symbol and period columns (errors)", () => {
    const s = sink();
    parseWideCsv("annual", "symbol,fiscal_year,revenue\n,2025,1\n", s);
    expect(codes(s)).toEqual(["W120_EMPTY_SYMBOL"]);
    const e1 = sink();
    parseWideCsv("annual", "name,fiscal_year\nA,2025\n", e1);
    expect(codes(e1)).toEqual(["E001_NO_SYMBOL"]);
    const e2 = sink();
    parseWideCsv("quarterly", "symbol,revenue\nA,1\n", e2);
    expect(codes(e2)).toEqual(["E007_NO_PERIOD"]);
  });

  it("enforces the row limit per CSV file (E004)", () => {
    const s = sink();
    const out = parseWideCsv("annual", "symbol,fiscal_year\nA,2024\nA,2025\nA,2026\n", s, { maxRows: 2 });
    expect(codes(s)).toEqual(["E004_TOO_LARGE"]);
    expect(out.annual).toEqual([]);
  });

  it("reads companies: type, basis, month names, snapshot ratios and market inputs", () => {
    const s = sink("c.csv");
    const csv = "symbol,name,sector,company_type,statement_basis,fy_end_month,price,price_date,shares_outstanding,face_value,market_cap,pe,price_book\n"
      + "a,Alpha Ltd,IT,Non-financial,Standalone,Dec,120,31-12-2025,5,2,600,20,3.5\n"
      + "b,Beta,Banks,bank lender?,sideways,13,,,,,,,\n";
    const out = parseWideCsv("companies", csv, s);
    expect(out.companies[0]).toEqual({
      symbol: "A", name: "Alpha Ltd", sector: "IT", company_type: "non_financial", statement_basis: "standalone", fy_end_month: 12,
      price: 120, price_date: "2025-12-31", shares_outstanding: 5, face_value: 2, market_cap_supplied: 600, snapshot: { pe: 20, pb: 3.5 },
    });
    expect(codes(s)).toEqual(["W118_BAD_VALUE", "W118_BAD_VALUE", "W118_BAD_VALUE"]);
    expect(out.companies[1]).toEqual({ symbol: "B", name: "Beta", sector: "Banks", snapshot: {} });
  });

  it("applies the money scale to ₹ crore fields only", () => {
    const s = sink();
    const a = parseWideCsv("annual", "symbol,fiscal_year,revenue,dividend_per_share,shares_outstanding_ye\nA,2026,250000,5,10\n", s, { moneyScale: "lakh" });
    expect(a.annual[0].row).toMatchObject({ revenue: 2500, dividend_per_share: 5, shares_outstanding_ye: 10 });
    const q = parseWideCsv("quarterly", "symbol,period_end,revenue\nA,2026-06-30,12000000000\n", s, { moneyScale: "rupee" });
    expect(q.quarterly[0].row.revenue).toBe(1200);
    const c = parseWideCsv("companies", "symbol,market_cap,price,isin\nA,5000,99,\n", s, { moneyScale: "million" });
    expect(c.companies[0]).toMatchObject({ market_cap_supplied: 500, price: 99 });
  });

  it("derives the fiscal year from a period end when fiscal_year is blank, and reads FY labels", () => {
    const s = sink();
    const a = parseWideCsv("annual", "symbol,fiscal_year,period_end,flags\nA,,2025-03-31,\nA,2024-25,,restated\nB,FY2023,,transition;odd\n", s, {
      fyEndMonthOf: () => 3,
    });
    expect(a.annual.map((e) => [e.symbol, e.row.fiscal_year, e.row.flags])).toEqual([["A", 2025, ["restated"]], ["B", 2023, ["transition"]]]); // the later FY2025 row wins
    expect(codes(s)).toEqual(["W113_DUPLICATE_PERIOD", "W118_BAD_VALUE"]);
  });
});

describe("joining files", () => {
  it("skips statement rows for symbols that no company file names (W115), and needs companies (E002)", async () => {
    const only = await importFiles([{ name: "annual.csv", text: "symbol,fiscal_year,revenue\nA,2026,10\n" }]);
    expect(only.dataset).toBeNull();
    expect(only.report.issues.map((i) => i.code)).toEqual(["E002_NO_COMPANIES", "W115_UNKNOWN_SYMBOL"]);
    expect(only.report.companiesRejected).toBe(1);
    const mixed = await importFiles([
      { name: "companies.csv", text: "symbol,name,sector,company_type\nA,Alpha,IT,non_financial\n" },
      { name: "annual.csv", text: "symbol,fiscal_year,revenue\nA,2026,10\nZ,2026,5\n" },
    ]);
    expect(mixed.report.ok).toBe(true);
    expect(mixed.dataset?.companies.map((c) => c.symbol)).toEqual(["A"]);
    expect(mixed.report.issues.find((i) => i.code === "W115_UNKNOWN_SYMBOL")?.message).toMatch(/Z/);
  });

  it("merges a snapshot file and a companies file for the same symbol", async () => {
    const out = await importFiles([
      { name: "snap.csv", text: "symbol,name,sector,pe,roce\nA,Alpha Ltd,IT,20,25\n" },
      { name: "companies.csv", text: "symbol,isin,company_type\nA,INE000A01019,non_financial\n" },
    ]);
    expect(out.report.ok).toBe(true);
    expect(out.dataset?.companies).toHaveLength(1);
    expect(out.dataset?.companies[0]).toMatchObject({ name: "Alpha Ltd", sector: "IT", isin: "INE000A01019", snapshot: { pe: 20, roce: 25 } });
  });

  it("adds statements from CSV to companies from a dataset JSON", async () => {
    const tiny = createTinyDataset();
    const out = await importFiles([
      { name: "extra.csv", text: "symbol,fiscal_year,revenue\nTINYSNAP,2026,900\n" },
      { name: "tiny.json", text: exportDatasetJson(tiny) },
    ]);
    expect(out.report.ok).toBe(true);
    expect(out.dataset?.companies.find((c) => c.symbol === "TINYSNAP")?.annual.map((r) => r.revenue)).toEqual([900]);
    expect(out.dataset?.meta.name).toBe(tiny.meta.name);
  });

  it("warns when the statement basis changes between years (W106) and records the latest basis", async () => {
    const out = await importFiles([
      { name: "c.csv", text: "symbol,name,sector,company_type\nA,Alpha,IT,non_financial\n" },
      { name: "a.csv", text: "symbol,fiscal_year,basis,revenue\nA,2025,consolidated,10\nA,2026,standalone,11\n" },
    ]);
    expect(out.report.issues.map((i) => i.code)).toContain("W106_BASIS_CHANGE");
    expect(out.dataset?.companies[0].statement_basis).toBe("standalone");
    const same = await importFiles([
      { name: "c.csv", text: "symbol,name,sector,company_type,statement_basis\nA,Alpha,IT,non_financial,standalone\n" },
      { name: "a.csv", text: "symbol,fiscal_year,basis,revenue\nA,2025,standalone,10\nA,2026,standalone,11\n" },
    ]);
    expect(same.report.issues.map((i) => i.code)).not.toContain("W106_BASIS_CHANGE");
  });

  it("notes the money scale in meta and says it does not apply to JSON or snapshot files", async () => {
    const out = await importFiles([
      { name: "c.csv", text: "symbol,name,sector,company_type\nA,Alpha,IT,non_financial\n" },
      { name: "a.csv", text: "symbol,fiscal_year,revenue\nA,2026,1000\n" },
      { name: "s.json", text: '[{"symbol":"B","market_cap":500}]' },
    ], { moneyScale: "lakh" });
    const by = (sym: string) => out.dataset?.companies.find((c) => c.symbol === sym);
    expect(by("A")?.annual[0].revenue).toBe(10);
    expect(by("B")?.market.market_cap_supplied).toBe(500);
    expect(out.dataset?.meta.notes).toContain("Amounts were converted from ₹ lakh to ₹ crore on import.");
    expect(out.report.issues.map((i) => i.code)).toContain("I002_SCALE_SCOPE");
  });
});
