// src/lib/sample/csv.ts — writes a dataset as the four wide CSV files (companies, annual,
// quarterly, shareholding) used for the public sample files (§F.5). Pure string building.
// Headers are the canonical field names of the dataset contract; a missing value is an empty
// cell (never 0); the first line is a "#" comment that the importer skips.
import type { CompanyRecord, FundamentalsDataset } from "@/lib/contracts";
import { ANNUAL_FIELDS, QUARTER_FIELDS, SHAREHOLDING_FIELDS } from "@/lib/contracts";

export interface WideCsvFiles {
  companies: string;
  annual: string;
  quarterly: string;
  shareholding: string;
}

/** Column order of companies.csv (identity, classification and market inputs). */
export const COMPANY_COLUMNS = [
  "symbol", "name", "sector", "industry", "isin", "company_type", "statement_basis", "fy_end_month",
  "price", "price_date", "shares_outstanding", "face_value", "sample_note",
] as const;

/** The provenance comment that opens every sample CSV (§F.5). */
export function sampleCsvComment(seed: number): string {
  return `# Fictional sample data generated by Funda Scanner (seed ${seed}). It describes no real company.`;
}

/** One CSV cell: empty for null, plain numbers, quoted text when needed. */
export function csvCell(v: string | number | null): string {
  if (v === null) return "";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "";
  return /[",\r\n]/.test(v) || v.trim() !== v ? `"${v.replace(/"/g, '""')}"` : v;
}

function line(cells: readonly (string | number | null)[]): string {
  return cells.map(csvCell).join(",");
}

function companyRow(c: CompanyRecord): (string | number | null)[] {
  return [
    c.symbol, c.name, c.sector, c.industry, c.isin, c.company_type, c.statement_basis, c.fy_end_month,
    c.market.price, c.market.price_date, c.market.shares_outstanding, c.market.face_value, c.sample_note,
  ];
}

function file(comment: string, header: readonly string[], rows: (string | number | null)[][]): string {
  return [comment, line(header), ...rows.map(line)].join("\n") + "\n";
}

/** Builds the four wide CSV files for a dataset. */
export function toWideCsv(ds: FundamentalsDataset, seed: number): WideCsvFiles {
  const comment = sampleCsvComment(seed);
  const companies = ds.companies;
  return {
    companies: file(comment, COMPANY_COLUMNS, companies.map(companyRow)),
    annual: file(
      comment,
      ["symbol", "fiscal_year", "period_end", "flags", ...ANNUAL_FIELDS],
      companies.flatMap((c) => c.annual.map((r) => [
        c.symbol, r.fiscal_year, r.period_end, r.flags.join(";"), ...ANNUAL_FIELDS.map((f) => r[f]),
      ])),
    ),
    quarterly: file(
      comment,
      ["symbol", "period_end", ...QUARTER_FIELDS],
      companies.flatMap((c) => c.quarterly.map((q) => [c.symbol, q.period_end, ...QUARTER_FIELDS.map((f) => q[f])])),
    ),
    shareholding: file(
      comment,
      ["symbol", "period_end", ...SHAREHOLDING_FIELDS],
      companies.flatMap((c) => c.shareholding.map((s) => [c.symbol, s.period_end, ...SHAREHOLDING_FIELDS.map((f) => s[f])])),
    ),
  };
}
