// src/lib/sample/index.ts — deterministic synthetic sample of FICTIONAL companies (§F).
// generateSampleDataset() is pure and synchronous: no clock, no Math.random, no module state.
// Each company has its own PRNG, mulberry32(fnv1a32(`${seed}:${slug}`)), so adding a company
// never reshuffles the others. Accounting identities are documented in gen-nonfinancial.ts,
// gen-lender.ts and gen-insurer.ts and checked by sample.test.ts for every company-year.
import type { AnnualRow, CompanyRecord, FundamentalsDataset } from "@/lib/contracts";
import { DATASET_SCHEMA, DATASET_VERSION } from "@/lib/contracts";
import {
  type RosterEntry, SAMPLE_COUNT, SECTORS, archetypeLabel, buildRoster, sampleNote,
} from "./archetypes";
import { LAST_FY, NEW_LISTING_FIRST_FY } from "./common";
import { drawInsurer, simulateInsurer } from "./gen-insurer";
import { drawLender, simulateLender } from "./gen-lender";
import { generateMarket } from "./gen-market";
import { drawNonFinancial, simulateNonFinancial } from "./gen-nonfinancial";
import { generateQuarters, ttmSum } from "./gen-quarterly";
import { generateShareholding } from "./gen-shareholding";
import { STEMS, companyName, companySymbol, stressName, stressSymbol } from "./names";
import { companyRng, pick } from "./prng";

export type { Archetype, SectorKey, Trait } from "./archetypes";
export { SAMPLE_COUNT } from "./archetypes";

/** Seed of the bundled sample (§F.1). */
export const SAMPLE_SEED = 24301;
/** Version of the generator; part of meta.generator. Bump when the output changes. */
export const GENERATOR_VERSION = "1.0.0";

/** Notes carried in meta.notes of every generated dataset. */
export const SAMPLE_NOTES: readonly string[] = [
  "Every company in this sample is fictional. Names, symbols and figures were generated and describe no real business.",
  "Fiscal-year labels are illustrative and describe no real period.",
  "Reference prices were generated to illustrate valuation ratios; no price date is given.",
];

/** A planned company: its roster profile plus the name and symbol it is published under. */
export interface SamplePlan {
  slug: string;
  symbol: string;
  name: string;
  entry: RosterEntry;
  stress: boolean;
}

/** The 150 planned companies of the bundled sample, in dataset order. */
export function samplePlans(): SamplePlan[] {
  return buildRoster().map((entry) => {
    const spec = SECTORS[entry.sectorKey];
    const stem = STEMS[entry.index];
    if (!stem) throw new Error(`No name stem for roster position ${entry.index}`);
    const noun = spec.nouns[entry.sectorIndex % spec.nouns.length];
    return { slug: entry.slug, symbol: companySymbol(stem, noun), name: companyName(stem, noun), entry, stress: false };
  });
}

/** Stress-set plans: profiles are reused in roster order with SYN symbols. */
function stressPlans(count: number): SamplePlan[] {
  const roster = buildRoster();
  const out: SamplePlan[] = [];
  for (let k = 1; k <= count; k++) {
    const entry = roster[(k - 1) % roster.length];
    out.push({ slug: `syn-${k}`, symbol: stressSymbol(k, count), name: stressName(k, count), entry, stress: true });
  }
  return out;
}

function sourceNote(seed: number): string {
  return `Fictional company generated by funda-sample ${GENERATOR_VERSION} (seed ${seed}).`;
}

/** Generates one company from its plan. Pure. */
export function generateCompany(plan: SamplePlan, seed: number): CompanyRecord {
  const { entry } = plan;
  const spec = SECTORS[entry.sectorKey];
  const rng = companyRng(seed, plan.slug);

  let sim: AnnualRow[];
  let faceValue: number;
  if (spec.family === "non_financial" && spec.nf) {
    const d = drawNonFinancial(spec.nf, entry.archetype, entry.traits, spec.faceValues, rng);
    sim = simulateNonFinancial(d, entry.archetype, entry.traits, rng);
    faceValue = d.faceValue;
  } else if (spec.family === "lender" && spec.lender) {
    const d = drawLender(spec.lender, entry.archetype, spec.faceValues, rng);
    sim = simulateLender(d, rng);
    faceValue = d.faceValue;
  } else if (spec.family === "insurer" && spec.insurer) {
    const d = drawInsurer(spec.insurer, spec.faceValues, rng);
    sim = simulateInsurer(d, rng);
    faceValue = d.faceValue;
  } else {
    throw new Error(`Sector ${spec.key} has no parameters for family ${spec.family}`);
  }

  const quarters = generateQuarters(sim, spec.seasonality, rng);
  const latest = sim.find((r) => r.fiscal_year === LAST_FY);
  if (!latest) throw new Error("Generator did not simulate the latest financial year");
  const promoterKind = pick(rng, spec.promoter);
  const shareholding = generateShareholding(promoterKind, entry.archetype, latest.revenue ?? 0, rng);
  const market = generateMarket({
    archetype: entry.archetype,
    sectorPe: spec.pe,
    sectorPs: spec.ps,
    shares: latest.shares_outstanding_ye ?? 0,
    faceValue,
    ttmOwners: ttmSum(quarters, "net_profit_owners"),
    ttmRevenue: ttmSum(quarters, "revenue"),
    latestDps: latest.dividend_per_share ?? 0,
  }, rng);

  const traits = entry.traits;
  const firstFy = traits.includes("new_listing") ? NEW_LISTING_FIRST_FY : sim[0].fiscal_year;
  const annual = sim.filter((r) => r.fiscal_year >= firstFy && r.fiscal_year <= LAST_FY);
  const note = plan.stress
    ? `A stress-test company generated from the "${archetypeLabel(entry.archetype)}" profile of the ${spec.sector} sector. It describes no real business.`
    : sampleNote(entry);

  return {
    symbol: plan.symbol,
    name: plan.name,
    sector: spec.sector,
    industry: spec.industries[entry.sectorIndex % spec.industries.length],
    isin: null,
    company_type: traits.includes("type_omitted") ? null : spec.companyType,
    statement_basis: traits.includes("standalone") ? "standalone" : "consolidated",
    fy_end_month: 3,
    market,
    annual,
    quarterly: traits.includes("no_quarterly") ? [] : quarters,
    shareholding: traits.includes("no_shareholding") ? [] : shareholding,
    snapshot: {},
    sample_note: note,
    source_note: sourceNote(seed),
  };
}

/** Wraps generated companies in a dataset with honest, undated synthetic metadata. */
export function buildSampleDataset(companies: CompanyRecord[], seed: number, name: string): FundamentalsDataset {
  return {
    schema: DATASET_SCHEMA,
    version: DATASET_VERSION,
    meta: {
      name,
      source: "synthetic_sample",
      isSynthetic: true,
      asOf: null,
      importedAt: null,
      currency: "INR",
      moneyUnit: "crore",
      sharesUnit: "crore",
      files: [],
      generator: { name: "funda-sample", version: GENERATOR_VERSION, seed },
      notes: [...SAMPLE_NOTES],
    },
    companies,
  };
}

/**
 * The synthetic sample. Defaults: seed 24301, 150 fictional companies (§F.1, §F.2).
 * A count up to 150 takes the first companies of the roster; a larger count builds the stress
 * set (symbols SYN0001…, names "Synthetic Company 0001 (stress test)").
 */
export function generateSampleDataset(o: { seed?: number; count?: number } = {}): FundamentalsDataset {
  const seed = o.seed ?? SAMPLE_SEED;
  const count = o.count ?? SAMPLE_COUNT;
  if (!Number.isInteger(count) || count < 0) throw new Error(`Sample count must be a whole number, got ${count}`);
  if (!Number.isInteger(seed)) throw new Error(`Sample seed must be a whole number, got ${seed}`);
  const stress = count > SAMPLE_COUNT;
  const plans = stress ? stressPlans(count) : samplePlans().slice(0, count);
  const companies = plans.map((p) => generateCompany(p, seed));
  const name = stress
    ? `Funda stress-test sample (${count} synthetic companies)`
    : `Funda sample (${count} fictional companies)`;
  return buildSampleDataset(companies, seed, name);
}

/** Generates only the named roster companies (by slug, in the order given), e.g. for public files. */
export function generateSampleSubset(slugs: readonly string[], seed: number = SAMPLE_SEED): FundamentalsDataset {
  const bySlug = new Map(samplePlans().map((p) => [p.slug, p]));
  const companies = slugs.map((slug) => {
    const plan = bySlug.get(slug);
    if (!plan) throw new Error(`Unknown sample slug "${slug}"`);
    return generateCompany(plan, seed);
  });
  return buildSampleDataset(companies, seed, `Funda sample (${companies.length} fictional companies)`);
}
