// Writes the public sample files (§F.5) with toMatchFileSnapshot. Regenerate after a generator
// change with `npm run sample:files` and commit the result; in CI a differing file fails here.
import { describe, expect, it } from "vitest";
import { ANNUAL_FIELDS, QUARTER_FIELDS, SHAREHOLDING_FIELDS, type FundamentalsDataset } from "@/lib/contracts";
import { denylistSymbolHits, denylistWordHits } from "@/test/fixtures/sample/real-name-denylist";
import { COMPANY_COLUMNS, csvCell, sampleCsvComment, toWideCsv } from "./csv";
import { SAMPLE_SEED, generateSampleSubset } from "./index";

/** The 12 archetype companies published as public sample files (roster slugs). */
const PUBLIC_SAMPLE_SLUGS: readonly string[] = [
  "fmcg-01", // compounder
  "metals-01", // cyclical
  "it-04", // cash-rich, debt-free
  "power-01", // leveraged utility
  "auto-03", // value trap
  "pharma-04", // turnaround
  "retail-02", // expensive grower
  "capgoods-05", // red flag: receivable build-up
  "telair-03", // loss-maker
  "chem-06", // new listing (4 financial years)
  "pvtbank-01", // good bank
  "insurer-01", // insurer, company type omitted
];

const DIR = "../../../public/sample-data";
const ds: FundamentalsDataset = generateSampleSubset(PUBLIC_SAMPLE_SLUGS, SAMPLE_SEED);
const json = JSON.stringify(ds, null, 2) + "\n";
const csv = toWideCsv(ds, SAMPLE_SEED);

/** Minimal RFC 4180 reader for the round-trip check (quotes, doubled quotes, commas). */
function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  for (const raw of text.split("\n")) {
    if (raw === "" || raw.startsWith("#")) continue;
    const cells: string[] = [];
    let cell = "";
    let quoted = false;
    for (let i = 0; i < raw.length; i++) {
      const ch = raw[i];
      if (quoted) {
        if (ch === '"' && raw[i + 1] === '"') {
          cell += '"';
          i++;
        } else if (ch === '"') quoted = false;
        else cell += ch;
      } else if (ch === '"') quoted = true;
      else if (ch === ",") {
        cells.push(cell);
        cell = "";
      } else cell += ch;
    }
    cells.push(cell);
    rows.push(cells);
  }
  return rows;
}

function asNum(s: string): number | null {
  return s === "" ? null : Number(s);
}

describe("public sample files", () => {
  it("contain 12 archetype companies, honestly labelled", () => {
    expect(ds.companies).toHaveLength(12);
    expect(ds.meta.isSynthetic).toBe(true);
    expect(ds.meta.asOf).toBeNull();
    expect(ds.meta.generator).toEqual({ name: "funda-sample", version: "1.0.0", seed: 24301 });
    for (const c of ds.companies) expect(c.market.price_date).toBeNull();
  });

  it("match the committed files", async () => {
    await expect(json).toMatchFileSnapshot(`${DIR}/funda-sample-12.json`);
    await expect(csv.companies).toMatchFileSnapshot(`${DIR}/funda-sample-companies.csv`);
    await expect(csv.annual).toMatchFileSnapshot(`${DIR}/funda-sample-annual.csv`);
    await expect(csv.quarterly).toMatchFileSnapshot(`${DIR}/funda-sample-quarterly.csv`);
    await expect(csv.shareholding).toMatchFileSnapshot(`${DIR}/funda-sample-shareholding.csv`);
  });

  it("start every CSV with the provenance comment and canonical headers", () => {
    const comment = sampleCsvComment(24301);
    expect(comment).toBe("# Fictional sample data generated by Funda Scanner (seed 24301). It describes no real company.");
    for (const text of Object.values(csv)) {
      expect(text.split("\n")[0]).toBe(comment);
      expect(text.endsWith("\n")).toBe(true);
    }
    expect(csv.companies.split("\n")[1]).toBe(COMPANY_COLUMNS.join(","));
    expect(csv.annual.split("\n")[1]).toBe(["symbol", "fiscal_year", "period_end", "flags", ...ANNUAL_FIELDS].join(","));
    expect(csv.quarterly.split("\n")[1]).toBe(["symbol", "period_end", ...QUARTER_FIELDS].join(","));
    expect(csv.shareholding.split("\n")[1]).toBe(["symbol", "period_end", ...SHAREHOLDING_FIELDS].join(","));
  });

  it("agree with the JSON, cell for cell (missing stays empty, never 0)", () => {
    const companies = parseCsv(csv.companies).slice(1);
    expect(companies.map((r) => r[0])).toEqual(ds.companies.map((c) => c.symbol));
    expect(companies.map((r) => r[1])).toEqual(ds.companies.map((c) => c.name));
    expect(companies.map((r) => r[12])).toEqual(ds.companies.map((c) => c.sample_note));

    const annual = parseCsv(csv.annual).slice(1);
    const expectedAnnual = ds.companies.flatMap((c) => c.annual.map((r) => ({ c, r })));
    expect(annual).toHaveLength(expectedAnnual.length);
    annual.forEach((cells, i) => {
      const { c, r } = expectedAnnual[i];
      expect(cells[0]).toBe(c.symbol);
      expect(Number(cells[1])).toBe(r.fiscal_year);
      expect(cells[3]).toBe(r.flags.join(";"));
      ANNUAL_FIELDS.forEach((f, k) => expect(asNum(cells[4 + k]), `${c.symbol} FY${r.fiscal_year} ${f}`).toBe(r[f]));
    });

    const quarterly = parseCsv(csv.quarterly).slice(1);
    expect(quarterly).toHaveLength(ds.companies.reduce((s, c) => s + c.quarterly.length, 0));
    const shareholding = parseCsv(csv.shareholding).slice(1);
    expect(shareholding).toHaveLength(ds.companies.reduce((s, c) => s + c.shareholding.length, 0));
    expect(JSON.parse(json)).toEqual(ds);
  });

  it("contain no real company, group or brand name", () => {
    for (const c of ds.companies) {
      expect(denylistWordHits(c.name), c.name).toEqual([]);
      expect(denylistSymbolHits(c.symbol), c.symbol).toEqual([]);
    }
    for (const text of [json, ...Object.values(csv)]) expect(denylistWordHits(text)).toEqual([]);
  });

  it("quotes CSV text only when needed", () => {
    expect(csvCell(null)).toBe("");
    expect(csvCell(12.5)).toBe("12.5");
    expect(csvCell(-3)).toBe("-3");
    expect(csvCell(Number.NaN)).toBe("");
    expect(csvCell("plain")).toBe("plain");
    expect(csvCell("a, b")).toBe('"a, b"');
    expect(csvCell('say "hi"')).toBe('"say ""hi"""');
    expect(csvCell(" padded")).toBe('" padded"');
  });
});
