// Generator tests for the synthetic sample (§E.4, §F). Archetype checks use simple local
// arithmetic on raw fields; calibration against the real metrics engine is an integration test.
import { readdirSync, readFileSync } from "node:fs";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { AnnualRow, CompanyRecord, Num } from "@/lib/contracts";
import { ANNUAL_FIELDS, LENDER_ONLY_FIELDS, QUARTER_FIELDS, SHAREHOLDING_FIELDS } from "@/lib/contracts";
import { ROSTER_CODES, SECTORS, SECTOR_ORDER, buildRoster, sampleNote } from "./archetypes";
import { quarterEnds } from "./common";
import {
  GENERATOR_VERSION, SAMPLE_COUNT, SAMPLE_SEED, type SamplePlan, generateSampleDataset, generateSampleSubset, samplePlans,
} from "./index";

const DS = generateSampleDataset();
const PLANS = samplePlans();
const PLAN_BY_SYMBOL = new Map<string, SamplePlan>(PLANS.map((p) => [p.symbol, p]));
const TOL = 0.011;

function plan(c: CompanyRecord): SamplePlan {
  const p = PLAN_BY_SYMBOL.get(c.symbol);
  if (!p) throw new Error(`No plan for ${c.symbol}`);
  return p;
}
function family(c: CompanyRecord) {
  return SECTORS[plan(c).entry.sectorKey].family;
}
function byArchetype(a: string): CompanyRecord[] {
  return DS.companies.filter((c) => plan(c).entry.archetype === a);
}
function withTrait(t: string): CompanyRecord[] {
  return DS.companies.filter((c) => (plan(c).entry.traits as readonly string[]).includes(t));
}
/** Reads a field that must be present. */
function n(r: AnnualRow, f: keyof AnnualRow): number {
  const v = r[f] as Num;
  if (v === null || v === undefined) throw new Error(`FY${r.fiscal_year} ${String(f)} is null`);
  return v;
}
function near(a: number, b: number, tol = TOL): boolean {
  return Math.abs(a - b) <= tol;
}
function fy(c: CompanyRecord, year: number): AnnualRow {
  const r = c.annual.find((x) => x.fiscal_year === year);
  if (!r) throw new Error(`${c.symbol} has no FY${year}`);
  return r;
}
function netWorth(r: AnnualRow): number {
  return n(r, "equity_share_capital") + n(r, "other_equity");
}
function centsOf(v: Num): number {
  return Math.round((v ?? 0) * 100);
}

describe("shape and metadata (§F.1)", () => {
  it("has 150 companies with honest, undated synthetic metadata", () => {
    expect(SAMPLE_SEED).toBe(24301);
    expect(SAMPLE_COUNT).toBe(150);
    expect(DS.schema).toBe("funda-dataset");
    expect(DS.version).toBe(1);
    expect(DS.companies).toHaveLength(150);
    expect(DS.meta).toMatchObject({
      source: "synthetic_sample", isSynthetic: true, asOf: null, importedAt: null, currency: "INR",
      moneyUnit: "crore", sharesUnit: "crore", files: [],
      generator: { name: "funda-sample", version: GENERATOR_VERSION, seed: 24301 },
    });
    expect(DS.meta.notes).toContain("Fiscal-year labels are illustrative and describe no real period.");
    expect(DS.meta.name).toMatch(/fictional/);
  });

  it("never invents a price date, an ISIN or a snapshot value", () => {
    for (const c of DS.companies) {
      expect(c.market.price_date).toBeNull();
      expect(c.market.market_cap_supplied).toBeNull();
      expect(c.isin).toBeNull();
      expect(c.snapshot).toEqual({});
      expect(c.fy_end_month).toBe(3);
      expect(c.sample_note).toBeTruthy();
      expect(c.source_note).toMatch(/^Fictional company generated by funda-sample/);
    }
  });

  it("publishes FY2016–FY2026, 13 quarters and 13 shareholding quarters, oldest first", () => {
    const ends = [...quarterEnds(2024), ...quarterEnds(2025), ...quarterEnds(2026), quarterEnds(2027)[0]];
    expect(ends[0]).toBe("2023-06-30");
    expect(ends[12]).toBe("2026-06-30");
    for (const c of DS.companies) {
      const t = plan(c).entry.traits;
      const years = c.annual.map((r) => r.fiscal_year);
      const first = t.includes("new_listing") ? 2023 : 2016;
      expect(years, c.symbol).toEqual(Array.from({ length: 2026 - first + 1 }, (_, i) => first + i));
      for (const r of c.annual) expect(r.period_end).toBe(`${r.fiscal_year}-03-31`);
      if (t.includes("no_quarterly")) expect(c.quarterly).toEqual([]);
      else expect(c.quarterly.map((q) => q.period_end), c.symbol).toEqual(ends);
      if (t.includes("no_shareholding")) expect(c.shareholding).toEqual([]);
      else expect(c.shareholding.map((s) => s.period_end), c.symbol).toEqual(ends);
    }
  });

  it("stores every key, with finite numbers or null, never NaN, −0 or undefined", () => {
    const bad: string[] = [];
    for (const c of DS.companies) {
      for (const r of c.annual) {
        for (const f of ANNUAL_FIELDS) {
          const v = r[f];
          if (!(f in r) || !(v === null || Number.isFinite(v)) || Object.is(v, -0)) bad.push(`${c.symbol} FY${r.fiscal_year} ${f}`);
        }
      }
      for (const q of c.quarterly) for (const f of QUARTER_FIELDS) if (!Number.isFinite(q[f])) bad.push(`${c.symbol} ${q.period_end} ${f}`);
      for (const s of c.shareholding) for (const f of SHAREHOLDING_FIELDS) if (!Number.isFinite(s[f])) bad.push(`${c.symbol} ${s.period_end} ${f}`);
      for (const v of Object.values(c.market)) if (!(v === null || typeof v === "number")) bad.push(`${c.symbol} market`);
    }
    expect(bad).toEqual([]);
  });

  it("rounds money to 2 decimals", () => {
    const bad: string[] = [];
    for (const c of DS.companies) {
      for (const r of c.annual) {
        for (const f of ANNUAL_FIELDS) {
          const v = r[f];
          if (v !== null && !near(v, Math.round(v * 100) / 100, 1e-9)) bad.push(`${c.symbol} FY${r.fiscal_year} ${f}`);
        }
      }
    }
    expect(bad).toEqual([]);
  });
});

describe("mix (§F.2)", () => {
  it("has the documented sector and family counts", () => {
    const count = (pred: (c: CompanyRecord) => boolean) => DS.companies.filter(pred).length;
    expect(count((c) => family(c) === "non_financial")).toBe(122);
    expect(count((c) => family(c) === "lender")).toBe(24);
    expect(count((c) => family(c) === "insurer")).toBe(4);
    const expected: Record<string, number> = {
      it: 12, fmcg: 10, pharma: 10, auto: 10, capgoods: 10, chem: 10, cement: 8, metals: 8, power: 8, realty: 8, oilgas: 6,
      retail: 6, textiles: 6, telair: 4, holding: 2, capmkt: 4, pvtbank: 8, psubank: 4, nbfc: 8, hfc: 4, insurer: 4,
    };
    for (const key of SECTOR_ORDER) {
      expect(ROSTER_CODES[key].length, key).toBe(expected[key]);
      expect(count((c) => plan(c).entry.sectorKey === key), key).toBe(expected[key]);
    }
    expect(count((c) => c.company_type === "other_financial")).toBe(4);
  });

  it("has the documented archetype and trait overlays", () => {
    const archetypes: Record<string, number> = {
      compounder: 14, cyclical: 10, cash_rich: 6, leveraged_utility: 6, value_trap: 6, turnaround: 6, expensive_grower: 6,
      dividend_payer: 6, rf_receivables: 2, rf_pledge: 2, rf_cash: 2, serial_diluter: 3, loss_maker: 4, negative_net_worth: 2,
      good_bank: 6, stressed_bank: 4,
    };
    for (const [a, k] of Object.entries(archetypes)) expect(byArchetype(a).length, a).toBe(k);
    const redFlagCases = byArchetype("rf_receivables").length + byArchetype("rf_pledge").length + byArchetype("rf_cash").length;
    expect(redFlagCases).toBe(6);
    const traits: Record<string, number> = {
      new_listing: 4, transition: 1, standalone: 4, no_quarterly: 4, no_shareholding: 3, type_omitted: 6,
    };
    for (const [t, k] of Object.entries(traits)) expect(withTrait(t).length, t).toBe(k);
  });

  it("gives each company a teaching note that matches its overlays", () => {
    for (const c of DS.companies) expect(c.sample_note).toBe(sampleNote(plan(c).entry));
    for (const c of withTrait("new_listing")) expect(c.sample_note).toMatch(/four financial years/);
    for (const c of byArchetype("cash_rich")) expect(c.sample_note).toMatch(/debt-free/);
  });

  it("uses the company type and basis implied by the traits", () => {
    for (const c of DS.companies) {
      const p = plan(c);
      const t = p.entry.traits;
      expect(c.company_type).toBe(t.includes("type_omitted") ? null : SECTORS[p.entry.sectorKey].companyType);
      expect(c.statement_basis).toBe(t.includes("standalone") ? "standalone" : "consolidated");
    }
    // Omitted types must be inferable from the sector name (§C.7 keywords).
    for (const c of withTrait("type_omitted")) {
      const f = family(c);
      if (f === "lender") expect(c.sector).toMatch(/bank|finance/i);
      if (f === "insurer") expect(c.sector).toMatch(/insurance/i);
      if (f === "non_financial") expect(c.sector).not.toMatch(/bank|finance|nbfc|insurance/i);
    }
  });
});

describe("accounting identities (§F.3), every company-year", () => {
  it("non-financial: P&L, roll-forwards, cash, equity and balance sheet", () => {
    for (const c of DS.companies.filter((x) => family(x) === "non_financial")) {
      const fv = c.market.face_value ?? NaN;
      const services = SECTORS[plan(c).entry.sectorKey].nf?.cogsShare === null;
      c.annual.forEach((r, i) => {
        const at = `${c.symbol} FY${r.fiscal_year}`;
        const ebitda = n(r, "revenue") - n(r, "operating_expenses");
        expect(near(n(r, "pbt"), ebitda + n(r, "other_income") - n(r, "depreciation") - n(r, "finance_cost") + n(r, "exceptional_items")), at).toBe(true);
        expect(near(n(r, "net_profit"), n(r, "pbt") - n(r, "tax_expense")), at).toBe(true);
        expect(n(r, "tax_expense") >= 0, at).toBe(true);
        if (n(r, "pbt") <= 0) expect(n(r, "tax_expense"), at).toBe(0);
        if (services) expect(r.cogs, at).toBeNull();
        else expect(n(r, "cogs") <= n(r, "operating_expenses") + TOL, at).toBe(true);
        expect(near(n(r, "equity_share_capital"), n(r, "shares_outstanding_ye") * fv), at).toBe(true);
        expect(n(r, "cash_and_bank") <= n(r, "total_current_assets") && n(r, "total_current_assets") <= n(r, "total_assets"), at).toBe(true);
        expect(n(r, "total_current_assets") + TOL >= n(r, "inventories") + n(r, "trade_receivables") + n(r, "cash_and_bank") + n(r, "current_investments"), at).toBe(true);
        expect(n(r, "total_current_liabilities") + TOL >= n(r, "trade_payables") + n(r, "borrowings_current"), at).toBe(true);
        expect(n(r, "total_assets") + TOL >= n(r, "total_current_assets") + n(r, "net_fixed_assets"), at).toBe(true);
        const visibleLiabilities = netWorth(r) + n(r, "non_controlling_interest") + n(r, "borrowings_non_current")
          + n(r, "lease_liabilities") + n(r, "total_current_liabilities");
        expect(n(r, "total_assets") + TOL >= visibleLiabilities, at).toBe(true);
        for (const f of ["revenue", "inventories", "trade_receivables", "trade_payables", "capex", "net_fixed_assets",
          "cash_and_bank", "borrowings_non_current", "borrowings_current", "lease_liabilities", "dividend_per_share",
          "equity_issuance", "current_investments", "depreciation", "finance_cost", "other_income"] as const) {
          expect(n(r, f) >= 0, `${at} ${f}`).toBe(true);
        }
        for (const f of LENDER_ONLY_FIELDS) expect(r[f], `${at} ${f}`).toBeNull();
        if (c.statement_basis === "standalone") {
          expect(n(r, "non_controlling_interest"), at).toBe(0);
          expect(n(r, "net_profit_owners"), at).toBe(n(r, "net_profit"));
        }

        if (i === 0) return;
        const p = c.annual[i - 1];
        const dividends = n(r, "dividend_per_share") * n(r, "shares_outstanding_ye");
        const tol = 0.05; // dividends = round2(dps × shares); the product itself is not rounded here
        expect(near(n(r, "net_fixed_assets"), n(p, "net_fixed_assets") + n(r, "capex") - n(r, "depreciation")), `${at} nfa`).toBe(true);
        const dWc = n(r, "trade_receivables") + n(r, "inventories") - n(r, "trade_payables")
          - (n(p, "trade_receivables") + n(p, "inventories") - n(p, "trade_payables"));
        expect(near(n(r, "cfo"), n(r, "net_profit") + n(r, "depreciation") - dWc), `${at} cfo`).toBe(true);
        const dDebt = n(r, "borrowings_non_current") + n(r, "borrowings_current") - n(p, "borrowings_non_current") - n(p, "borrowings_current");
        expect(near(n(r, "cash_and_bank"), n(p, "cash_and_bank") + n(r, "cfo") - n(r, "capex") - dividends + dDebt + n(r, "equity_issuance"), tol), `${at} cash`).toBe(true);
        const premium = n(r, "equity_issuance") - (n(r, "equity_share_capital") - n(p, "equity_share_capital"));
        expect(near(n(r, "other_equity"), n(p, "other_equity") + n(r, "net_profit_owners") - dividends + premium, tol), `${at} equity`).toBe(true);
        expect(near(n(r, "non_controlling_interest"), n(p, "non_controlling_interest") + n(r, "net_profit") - n(r, "net_profit_owners")), `${at} nci`).toBe(true);
        expect(near(n(r, "current_investments"), n(p, "current_investments")), `${at} current investments`).toBe(true);
      });
    }
  });

  it("lenders: P&L, NPA, cash and equity; non-lender fields stay null", () => {
    for (const c of DS.companies.filter((x) => family(x) === "lender")) {
      const fv = c.market.face_value ?? NaN;
      c.annual.forEach((r, i) => {
        const at = `${c.symbol} FY${r.fiscal_year}`;
        const pbt = n(r, "revenue") - n(r, "interest_expended") + n(r, "other_income") - n(r, "operating_expenses")
          - n(r, "depreciation") - n(r, "provisions_contingencies") + n(r, "exceptional_items");
        expect(near(n(r, "pbt"), pbt), at).toBe(true);
        expect(near(n(r, "net_profit"), n(r, "pbt") - n(r, "tax_expense")), at).toBe(true);
        expect(n(r, "net_profit_owners")).toBe(n(r, "net_profit"));
        expect(n(r, "gross_npa") >= n(r, "net_npa") && n(r, "net_npa") >= 0, at).toBe(true);
        expect(n(r, "advances") > 0 && n(r, "total_assets") > n(r, "advances"), at).toBe(true);
        expect(n(r, "total_assets") + TOL >= netWorth(r) + n(r, "borrowings_non_current"), at).toBe(true);
        expect(near(n(r, "equity_share_capital"), n(r, "shares_outstanding_ye") * fv), at).toBe(true);
        for (const f of ["cogs", "finance_cost", "borrowings_current", "lease_liabilities", "trade_payables",
          "total_current_liabilities", "net_fixed_assets", "inventories", "trade_receivables", "current_investments",
          "total_current_assets", "capex"] as const) {
          expect(r[f], `${at} ${f}`).toBeNull();
        }
        if (i === 0) return;
        const p = c.annual[i - 1];
        const dividends = n(r, "dividend_per_share") * n(r, "shares_outstanding_ye");
        const dBorrow = n(r, "borrowings_non_current") - n(p, "borrowings_non_current");
        expect(near(n(r, "cash_and_bank"), n(p, "cash_and_bank") + n(r, "cfo") - dividends + dBorrow + n(r, "equity_issuance"), 0.05), `${at} cash`).toBe(true);
        const premium = n(r, "equity_issuance") - (n(r, "equity_share_capital") - n(p, "equity_share_capital"));
        expect(near(n(r, "other_equity"), n(p, "other_equity") + n(r, "net_profit") - dividends + premium, 0.05), `${at} equity`).toBe(true);
      });
    }
  });

  it("insurers: minimal fields only, with consistent profit, cash and equity", () => {
    const filled = new Set(["revenue", "operating_expenses", "depreciation", "pbt", "tax_expense", "net_profit",
      "net_profit_owners", "dividend_per_share", "equity_share_capital", "other_equity", "total_assets", "cash_and_bank",
      "shares_outstanding_ye", "cfo", "equity_issuance"]);
    for (const c of DS.companies.filter((x) => family(x) === "insurer")) {
      c.annual.forEach((r, i) => {
        const at = `${c.symbol} FY${r.fiscal_year}`;
        for (const f of ANNUAL_FIELDS) {
          if (filled.has(f)) expect(r[f], `${at} ${f}`).not.toBeNull();
          else expect(r[f], `${at} ${f}`).toBeNull();
        }
        expect(near(n(r, "pbt"), n(r, "revenue") - n(r, "operating_expenses") - n(r, "depreciation")), at).toBe(true);
        expect(near(n(r, "net_profit"), n(r, "pbt") - n(r, "tax_expense")), at).toBe(true);
        if (i === 0) return;
        const p = c.annual[i - 1];
        const dividends = n(r, "dividend_per_share") * n(r, "shares_outstanding_ye");
        expect(near(n(r, "cash_and_bank"), n(p, "cash_and_bank") + n(r, "cfo") - dividends, 0.05), at).toBe(true);
        expect(near(n(r, "other_equity"), n(p, "other_equity") + n(r, "net_profit") - dividends, 0.05), at).toBe(true);
      });
    }
  });

  it("four quarters sum exactly to each published financial year", () => {
    let checked = 0;
    for (const c of DS.companies) {
      if (c.quarterly.length === 0) continue;
      for (const year of [2024, 2025, 2026]) {
        const ends = quarterEnds(year);
        const qs = c.quarterly.filter((q) => ends.includes(q.period_end));
        expect(qs, `${c.symbol} FY${year}`).toHaveLength(4);
        const row = fy(c, year);
        for (const f of QUARTER_FIELDS) {
          const annual = f === "net_profit_owners" ? row.net_profit_owners ?? row.net_profit : row[f];
          const sumCents = qs.reduce((s, q) => s + centsOf(q[f]), 0);
          expect(sumCents, `${c.symbol} FY${year} ${f}`).toBe(centsOf(annual));
          const sum = qs.reduce((s, q) => s + (q[f] ?? 0), 0);
          expect(near(sum, annual ?? NaN, 1e-6), `${c.symbol} FY${year} ${f}`).toBe(true);
          checked++;
        }
      }
    }
    expect(checked).toBeGreaterThan(146 * 3 * 4);
  });

  it("publishes the first quarter of FY2027, so TTM differs from FY2026", () => {
    for (const c of DS.companies.filter((x) => x.quarterly.length > 0)) {
      const ttm = c.quarterly.slice(-4).reduce((s, q) => s + (q.revenue ?? 0), 0);
      expect(near(ttm, fy(c, 2026).revenue ?? NaN, 0.5), c.symbol).toBe(false);
    }
  });

  it("keeps shareholding totals at or below 100", () => {
    for (const c of DS.companies) {
      for (const s of c.shareholding) {
        const at = `${c.symbol} ${s.period_end}`;
        const total = (s.promoter_pct ?? 0) + (s.fii_pct ?? 0) + (s.dii_pct ?? 0);
        expect(total <= 100, at).toBe(true);
        for (const v of [s.promoter_pct, s.fii_pct, s.dii_pct, s.promoter_pledged_pct]) expect(v !== null && v >= 0 && v <= 100, at).toBe(true);
        expect(Number.isInteger(s.num_shareholders), at).toBe(true);
        if (s.promoter_pct === 0) expect(s.promoter_pledged_pct, at).toBe(0);
      }
    }
  });
});

describe("validation-style sanity (the W1xx checks of §E.3)", () => {
  it("has plausible units: crore money, percent numbers, crore shares, DPS below price", () => {
    const revenues = DS.companies.map((c) => fy(c, 2026).revenue ?? 0).sort((a, b) => a - b);
    expect(revenues[Math.floor(revenues.length / 2)]).toBeLessThan(1e7);
    for (const c of DS.companies) {
      expect(c.market.shares_outstanding ?? Infinity, c.symbol).toBeLessThan(1e5);
      expect(c.market.shares_outstanding, c.symbol).toBe(fy(c, 2026).shares_outstanding_ye);
      expect(c.market.price ?? 0, c.symbol).toBeGreaterThan(fy(c, 2026).dividend_per_share ?? 0);
      expect(c.market.price ?? 0, c.symbol).toBeGreaterThanOrEqual(1);
      expect(SECTORS[plan(c).entry.sectorKey].faceValues).toContain(c.market.face_value);
    }
    const promoterValues = DS.companies.flatMap((c) => c.shareholding.map((s) => s.promoter_pct ?? 0));
    expect(promoterValues.some((v) => v > 1)).toBe(true);
  });
});

describe("archetype intent (local arithmetic on raw fields)", () => {
  const capitalEmployed = (r: AnnualRow) => netWorth(r) + n(r, "non_controlling_interest") + n(r, "borrowings_non_current")
    + n(r, "borrowings_current") + n(r, "lease_liabilities");
  const ebit = (r: AnnualRow) => n(r, "revenue") - n(r, "operating_expenses") + n(r, "other_income") - n(r, "depreciation");
  const roceAvg5 = (c: CompanyRecord) => {
    let total = 0;
    for (let year = 2022; year <= 2026; year++) {
      total += (ebit(fy(c, year)) / ((capitalEmployed(fy(c, year)) + capitalEmployed(fy(c, year - 1))) / 2)) * 100;
    }
    return total / 5;
  };
  const cagr = (c: CompanyRecord, field: keyof AnnualRow, years: number) => {
    const end = n(fy(c, 2026), field);
    const start = n(fy(c, 2026 - years), field);
    let lo = -1;
    let hi = 2;
    for (let k = 0; k < 60; k++) {
      const mid = (lo + hi) / 2;
      let g = 1;
      for (let j = 0; j < years; j++) g *= 1 + mid;
      if (start * g < end) lo = mid;
      else hi = mid;
    }
    return lo * 100;
  };
  const ttmEps = (c: CompanyRecord) => c.quarterly.slice(-4).reduce((s, q) => s + (q.net_profit_owners ?? 0), 0) / (c.market.shares_outstanding ?? NaN);

  it("compounders earn high returns and grow at double digits", () => {
    for (const c of byArchetype("compounder")) {
      expect(roceAvg5(c), c.symbol).toBeGreaterThan(15);
      expect(cagr(c, "revenue", 5), c.symbol).toBeGreaterThan(10);
      expect(cagr(c, "net_profit", 5), c.symbol).toBeGreaterThan(10);
    }
  });

  it("cash-rich companies never borrow, so their finance cost is exactly 0", () => {
    for (const c of byArchetype("cash_rich")) {
      for (const r of c.annual) {
        expect(r.finance_cost, `${c.symbol} FY${r.fiscal_year}`).toBe(0);
        expect(n(r, "borrowings_non_current") + n(r, "borrowings_current") + n(r, "lease_liabilities")).toBe(0);
      }
    }
  });

  it("leveraged utilities borrow more than their equity", () => {
    for (const c of byArchetype("leveraged_utility")) {
      const r = fy(c, 2026);
      expect((n(r, "borrowings_non_current") + n(r, "borrowings_current")) / netWorth(r), c.symbol).toBeGreaterThan(1);
    }
  });

  it("value traps shrink while trading at a low P/E", () => {
    for (const c of byArchetype("value_trap")) {
      expect(n(fy(c, 2026), "revenue"), c.symbol).toBeLessThan(n(fy(c, 2021), "revenue"));
      const pe = (c.market.price ?? NaN) / ttmEps(c);
      expect(pe, c.symbol).toBeGreaterThan(0);
      expect(pe, c.symbol).toBeLessThan(10);
    }
  });

  it("turnarounds move from recent losses back to profit", () => {
    for (const c of byArchetype("turnaround")) {
      // Loss years FY2020–FY2024, including the first year of the 3-year window the template reads.
      expect(c.annual.filter((r) => r.fiscal_year >= 2020 && r.fiscal_year <= 2024).every((r) => n(r, "net_profit") < 0), c.symbol).toBe(true);
      expect(n(fy(c, 2024), "net_profit"), c.symbol).toBeLessThan(0);
      expect(n(fy(c, 2026), "net_profit"), c.symbol).toBeGreaterThan(0);
      expect(c.quarterly.slice(-4).reduce((s, q) => s + (q.net_profit ?? Number.NaN), 0), c.symbol).toBeGreaterThan(0);
    }
  });

  it("expensive growers grow fast and carry a very high P/E", () => {
    for (const c of byArchetype("expensive_grower")) {
      const years = withTrait("new_listing").includes(c) ? 3 : 5;
      expect(cagr(c, "revenue", years), c.symbol).toBeGreaterThan(20);
      expect((c.market.price ?? NaN) / ttmEps(c), c.symbol).toBeGreaterThan(60);
    }
  });

  it("dividend payers pay out most of their profit", () => {
    for (const c of byArchetype("dividend_payer")) {
      const r = fy(c, 2026);
      const payout = (n(r, "dividend_per_share") * n(r, "shares_outstanding_ye")) / n(r, "net_profit_owners");
      expect(payout, c.symbol).toBeGreaterThan(0.6);
      expect(payout, c.symbol).toBeLessThan(1);
    }
  });

  it("receivable build-up: debtor days up more than 30% in 3 years on slow sales growth", () => {
    for (const c of byArchetype("rf_receivables")) {
      const dd = (r: AnnualRow) => (n(r, "trade_receivables") / n(r, "revenue")) * 365;
      expect(dd(fy(c, 2026)) / dd(fy(c, 2023)), c.symbol).toBeGreaterThan(1.3);
      expect(cagr(c, "revenue", 3), c.symbol).toBeLessThan(10);
    }
  });

  it("high pledge: above 25% of the promoter holding and rising over a year", () => {
    for (const c of byArchetype("rf_pledge")) {
      const s = c.shareholding;
      const last = s[s.length - 1].promoter_pledged_pct ?? 0;
      const yearAgo = s[s.length - 5].promoter_pledged_pct ?? 0;
      expect(last, c.symbol).toBeGreaterThan(25);
      expect(last - yearAgo, c.symbol).toBeGreaterThan(5);
    }
    const others = DS.companies.filter((c) => plan(c).entry.archetype !== "rf_pledge");
    for (const c of others) for (const s of c.shareholding) expect(s.promoter_pledged_pct ?? 0, c.symbol).toBeLessThanOrEqual(10);
  });

  it("weak cash conversion: 5-year CFO below 70% of 5-year profit", () => {
    for (const c of byArchetype("rf_cash")) {
      const last5 = c.annual.slice(-5);
      const ratio = last5.reduce((s, r) => s + n(r, "cfo"), 0) / last5.reduce((s, r) => s + n(r, "net_profit"), 0);
      expect(ratio, c.symbol).toBeLessThan(0.7);
    }
  });

  it("serial diluters grow their share count by more than 5% every year", () => {
    for (const c of byArchetype("serial_diluter")) {
      for (let year = 2017; year <= 2026; year++) {
        const growth = n(fy(c, year), "shares_outstanding_ye") / n(fy(c, year - 1), "shares_outstanding_ye") - 1;
        expect(growth, `${c.symbol} FY${year}`).toBeGreaterThan(0.05);
      }
    }
  });

  it("loss-makers lose money and are priced on sales", () => {
    for (const c of byArchetype("loss_maker")) {
      expect(n(fy(c, 2026), "net_profit"), c.symbol).toBeLessThan(0);
      expect(ttmEps(c), c.symbol).toBeLessThan(0);
      for (const r of c.annual) expect(n(r, "dividend_per_share")).toBe(0);
    }
  });

  it("negative net worth companies end with equity below zero", () => {
    for (const c of byArchetype("negative_net_worth")) {
      expect(netWorth(fy(c, 2026)), c.symbol).toBeLessThan(0);
      expect(netWorth(fy(c, 2016)), c.symbol).toBeGreaterThan(0);
    }
  });

  it("good banks stay profitable with few bad loans; stressed banks had losses and high GNPA", () => {
    const gnpa = (r: AnnualRow) => (n(r, "gross_npa") / (n(r, "advances") + n(r, "gross_npa") - n(r, "net_npa"))) * 100;
    for (const c of byArchetype("good_bank")) {
      for (const r of c.annual) expect(n(r, "net_profit"), `${c.symbol} FY${r.fiscal_year}`).toBeGreaterThan(0);
      expect(gnpa(fy(c, 2026)), c.symbol).toBeLessThan(3);
    }
    for (const c of byArchetype("stressed_bank")) {
      expect(c.annual.some((r) => n(r, "net_profit") < 0), c.symbol).toBe(true);
      const peak = Math.max(...c.annual.map(gnpa));
      expect(peak, c.symbol).toBeGreaterThan(1.8 * gnpa(fy(c, 2026)));
      expect(c.annual.some((r) => n(r, "equity_issuance") > 0), c.symbol).toBe(true);
    }
  });

  it("the transition company flags FY2021 only", () => {
    const [c] = withTrait("transition");
    for (const r of c.annual) expect(r.flags).toEqual(r.fiscal_year === 2021 ? ["transition"] : []);
    for (const other of DS.companies.filter((x) => x !== c)) for (const r of other.annual) expect(r.flags).toEqual([]);
  });
});

describe("names and symbols (§F.4)", () => {
  it("uses unique invented upper-case symbols of 5–10 letters and unique names", () => {
    const symbols = DS.companies.map((c) => c.symbol);
    expect(new Set(symbols).size).toBe(150);
    for (const s of symbols) expect(s).toMatch(/^[A-Z]{5,10}$/);
    const names = DS.companies.map((c) => c.name);
    expect(new Set(names).size).toBe(150);
    for (const name of names) expect(name).toMatch(/^[A-Z][a-z]+ [A-Za-z ]+ Ltd$/);
  });
});

describe("determinism (§F.1, §F.3)", () => {
  afterEach(() => {
    vi.useRealTimers();
    vi.restoreAllMocks();
  });

  it("generates deep-equal output twice, whatever the clock says, without Math.random", () => {
    const random = vi.spyOn(Math, "random");
    vi.useFakeTimers();
    vi.setSystemTime("2031-01-15T10:00:00Z");
    const a = generateSampleDataset();
    vi.setSystemTime("1999-07-01T00:00:00Z");
    const b = generateSampleDataset({ seed: SAMPLE_SEED, count: SAMPLE_COUNT });
    expect(a).toEqual(b);
    expect(JSON.stringify(a)).toBe(JSON.stringify(DS));
    expect(random).not.toHaveBeenCalled();
  });

  it("gives every company its own stream: subsets and prefixes match the full sample", () => {
    const first10 = generateSampleDataset({ count: 10 });
    expect(first10.companies).toEqual(DS.companies.slice(0, 10));
    const subset = generateSampleSubset(["power-03", "it-01"]);
    expect(subset.companies[0]).toEqual(DS.companies[PLANS.findIndex((p) => p.slug === "power-03")]);
    expect(subset.companies[1]).toEqual(DS.companies[0]);
    expect(generateSampleDataset({ count: 0 }).companies).toEqual([]);
  });

  it("changes the figures, not the roster, with another seed", () => {
    const other = generateSampleDataset({ seed: 7 });
    expect(other.meta.generator?.seed).toBe(7);
    expect(other.companies.map((c) => c.symbol)).toEqual(DS.companies.map((c) => c.symbol));
    expect(other.companies[0].annual[0].revenue).not.toBe(DS.companies[0].annual[0].revenue);
  });

  it("rejects counts and seeds that are not whole numbers", () => {
    expect(() => generateSampleDataset({ count: -1 })).toThrow(/whole number/);
    expect(() => generateSampleDataset({ count: 2.5 })).toThrow(/whole number/);
    expect(() => generateSampleDataset({ seed: 1.5 })).toThrow(/whole number/);
    expect(() => generateSampleSubset(["nope-01"])).toThrow(/Unknown sample slug/);
  });

  it("uses only + − × ÷ and Math.round/floor/min/max/abs/sqrt, and never reads the clock", () => {
    const dir = "src/lib/sample";
    const sources = readdirSync(dir).filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts"));
    expect(sources.length).toBeGreaterThanOrEqual(11);
    for (const f of sources) {
      const code = readFileSync(`${dir}/${f}`, "utf8").replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/.*$/gm, "");
      const mathCalls = code.match(/Math\.[a-zA-Z0-9]+/g) ?? [];
      for (const m of mathCalls) expect(["Math.round", "Math.floor", "Math.min", "Math.max", "Math.abs", "Math.sqrt", "Math.imul"], `${f}: ${m}`).toContain(m);
      expect(code, f).not.toMatch(/\*\*/);
      expect(code, f).not.toMatch(/\bDate\b/);
      expect(code, f).not.toMatch(/performance\.now|crypto\./);
    }
  });
});

describe("stress set (§F.1)", () => {
  it("builds 5,000 synthetic companies with SYN symbols and stress-test names", () => {
    const big = generateSampleDataset({ count: 5000 });
    expect(big.companies).toHaveLength(5000);
    expect(big.companies[0].symbol).toBe("SYN0001");
    expect(big.companies[4999].symbol).toBe("SYN5000");
    expect(big.companies[0].name).toBe("Synthetic Company 0001 (stress test)");
    expect(new Set(big.companies.map((c) => c.symbol)).size).toBe(5000);
    expect(big.meta.isSynthetic).toBe(true);
    expect(big.meta.name).toMatch(/stress-test/);
    for (const c of big.companies.slice(0, 300)) {
      expect(c.sample_note).toMatch(/stress-test company/);
      expect(c.annual.length).toBeGreaterThanOrEqual(4);
    }
    // Profiles cycle through the roster, so the stress set keeps the sample's mix.
    const roster = buildRoster();
    expect(big.companies[150].sector).toBe(SECTORS[roster[0].sectorKey].sector);
  });
});
